### ISSUE TITLE
Heroku Not Working

### ISSUE THREAD

**Issue by CheddarAnon** [chrisbodhi/horsemen#1]
Hey!  
Searching the internet for information on the program. Confused what they mean by job specific long and short, but stumbled upon this and wanted to give you a headsup. 

If you have any insight what they meant that would be cool too lol

Thanks!

**Comment by chrisbodhi** [comment]
Hey, I somehow missed this. Thanks for the heads up! After Heroku switched off their free tier, all of my apps broke. Ah, well. 

As to your other question -- as I understand it, "long" and "short" refer to how long the session under the "Job specific" heading would take. Starting from [page 30 here](https://thepinnacleselfdotcom.files.wordpress.com/2014/06/horseman-workout-program.pdf), a session that takes 60 minutes, for instance, would be considered "long" (D'yer Maker), but Cottage Cheese would be "short."

Hope that helps, and good hunting.
